# 1. Build Stage
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /app

# Copy the csproj into a matching subfolder and restore
COPY BuildMate/*.csproj ./BuildMate/
RUN dotnet restore BuildMate/*.csproj

# Copy the rest of the files into the subfolder
COPY BuildMate-WEB/ ./BuildMate/

# Publish from the subdirectory
RUN dotnet publish BuildMate/*.csproj -c Release -o out

# 2. Runtime Stage
FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
COPY --from=build /app/out ./

ENTRYPOINT ["dotnet", "BuildMate.dll"]
